project2/Q/Cloq/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.login, name="home"),
    path('dashboard', views.dash, name ='dash'),
    path('admin_dashboard', views.admin_dash, name = "admin_dash"),
    path('availability', views.availability, name = "availability"),
    path('schedule/<int:year>/<int:month>/<int:day>/', views.schedule, name="schedule"),
    path('admin_schedule/<int:year>/<int:month>/<int:day>/', views.admin_schedule, name="admin_schedule"),
    path('settings', views.settings, name="settings"),
    path('admin_settings', views.admin_settings, name="admin_settings"),
    path('login', views.login, name="login"),
    path('logout', auth_views.logout, {'template_name': 'catalog/logout.html'}, name="logout"),
]

project2/Q/Cloq/models.py
from django.db import models
from django import forms
from datetime import datetime
from django.core.validators import RegexValidator
from django.contrib.auth.hashers import make_password

class user(models.Model):
    """
    Model for users:
        uid: integer: User identification number.
        usertype: integer: User type (1 = user, 2 = admin).
        firstname: string: User's first name.
        lastname: string: User's last name.
        username: string: User's username (used to login).
        password: string: Salted and hashed user password.
        email: string: User's email address.
        notification: boolean: Whether user wants to receive email notifications.
        pronoun: string: User's preferred pronouns.
        phone: string: User's phone number.
        overtime: boolean: Whether user wants to work overtime.
    """
    uid = models.AutoField(primary_key = True, help_text="User identifier.")
    usertype = models.IntegerField(help_text = "User type (1 = user, 2 = admin).")
    firstname = models.CharField(max_length=100, help_text = "First name.")
    lastname = models.CharField(max_length=100, help_text = "Last name.")
    username = models.CharField(max_length=30, help_text = "Username.")
    password = models.CharField(max_length=255, help_text = "Hashed user password.")
    email = models.EmailField(help_text = "User email.")
    notification = models.BooleanField(help_text = "Receive email notifications?")
    pronoun = models.CharField(max_length=30,blank=True,default="they/them/theirs", help_text = "User pronouns.")
    phone_regex = RegexValidator(regex=r'^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$', message="Phone number must be entered in the format: '+1 (888) 888-8888'.")
    phone = models.CharField(validators=[phone_regex], max_length=20, help_text = "User phone number.", default="+1 (888) 888-8888")
    overtime = models.BooleanField(help_text = "Work overtime?")
    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    def __str__(self):
        return str(self.firstname) + " " + str(self.lastname)

class announcement(models.Model):
    """
    Model for announcement:
        aid: integer: Announcement identification number.
        text: string: Announcement body string.
        time: datetime: Announcement datetime timestamp.
        usertype: integer: Viewable by (1 = all users, 2 = admins only).
        title: string: Announcement title string.
    """
    aid = models.AutoField(primary_key = True, help_text = "Announcement identifier.")
    text = models.TextField(help_text = "Announcement body.")
    time = models.DateTimeField(default=datetime.now, help_text="Announcement datetime.")
    usertype = models.IntegerField(help_text = "Viewable by (1 = all users, 2 = admins only)")
    title = models.CharField(max_length=255, help_text = "Announcement title.")

    def __str__(self):
        return str(self.title)

class time(models.Model):
    """
    Model for time:
        tid: integer: Timestamp identification number.
        timetype: integer: Time type (1 = punch in, 2 = punch out, 3 = shift, 4 = unavailable, 5 = request)
        start: datetime: Start datetime.
        end: datetime: End datetime.
        uid: integer: Associated user ID.
    """
    tid = models.AutoField(primary_key = True, help_text = "Timestamp identifier.")
    timetype = models.IntegerField(help_text = "Time type (1 = punch in, 2 = punch out, 3 = shift, 4 = unavailable, 5 = request)")
    start = models.DateTimeField(default=datetime.now, help_text = "Start datetime.")
    end = models.DateTimeField(default=datetime.now, help_text = "End datetime.")
    uid = models.IntegerField(help_text = "Associated user ID.")

    def __str__(self):
        return self.start.strftime("%m/%d/%Y (%H:%M)") + " - " + self.end.strftime("%m/%d/%Y (%H:%M)")

project2/Q/Cloq/templates/catalog/admin_dash.html
{% extends "template.html" %}

{% block content %}

<script>
document.getElementById("admin_dash").className += " active";
</script>

  <h2>Announcements</h2>
  <div class="table-responsive">
    <table class="table table-striped table-sm">
      <thead>
      <tr>
        <th>Date</th>
        <th>Notes</th>
      </tr>
      </thead>
      <tbody>
      {% for announce in announcements %}
      <tr>
        <td>{{ announce.time }}</td>
        <td>
          <a href="#" data-toggle="modal" data-target="#bannerformmodal{{announce.aid}}">{{ announce.title }}</a>
          <div class="modal fade bannerformmodal" tabindex="-1" role="dialog" aria-labelledby="bannerformmodal" aria-hidden="true" id="bannerformmodal{{announce.aid}}">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">{{ announce.title }}</h4>
                  </div>
                  <div class="modal-body">
                    {{ announce.text }}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    Delete Announcement
                  </div>
                </div>
              </div>
            </div>
          </div>
        </td>
      </tr>
      {% endfor %}


        <br>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#makeAnnouncement" data-whatever="@mdo">Add additional announcement</button>
          <div class="modal fade" id="makeAnnouncement" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                  <div class="modal-content">
                      <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel">New annoucement</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>
                      </div>
                      <div class="modal-body">
                          <form action="" method="post">
                              {% csrf_token %}
                              <div class="form-group">
                                  <label for="announcement-name" class="col-form-label">Title:</label>
                                  <input type="text" class="form-control" name="title" id="announcement-name" required>
                              </div>
                              <div class="form-group">
                                  <label for="announcement-text" class="col-form-label">Message:</label>
                                  <textarea class="form-control" name ="text" id="announcement-text" value="{{text}}" required></textarea>
                              </div>
                              <div class="form-group">
                                  <label for="selectWhoSee">Who can see:</label>
                                  <select class="form-control" id="selectWhoSee" name="usertype" value ="{{usertype}}" required>
                                      <option>Admins Only</option>
                                      <option>Everyone</option>
                                  </select>
                              </div>
                              <div class="modal-footer">
                                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                  <input type="submit" class="btn btn-primary" value ="Submit Annoucement">
                              </div>
                          </form>
                      </div>
                  </div>
              </div>
          </div>
        <br>
        <br>
      </tbody>

    </table>

    </div>

    <h2>Today's Schedule</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <!--<th>Location</th>-->
                <th>Name</th>
                <th>Start</th>
                <th>End</th>
            </tr>
            </thead>
            <tbody>
            {% for first_n, last_n, user_id, start_t, end_t in today_users %}
            <tr>
                <!--<td>Hamp (DC)</td>-->
                <td>{{ first_n }} {{last_n}}</td>
                <td>{{ start_t }}</td>
                <td>{{ end_t }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

project2/Q/Cloq/templates/catalog/admin_schedule.html
{% extends "template.html" %}

{% block content %}
{% load static %}

<script>
document.getElementById("admin_schedule").className += " active";
</script>

<link href= "{% static 'css/scheduler.css' %}" rel="stylesheet">
<table>
    <td style="width:10%">
        <button type="button" class="btn btn-outline-primary">Modify Schedule</button>
    </td>
    <td style="width:80%">
        <nav aria-label="Scheduler">
          <ul class="pagination justify-content-center pagination-lg">
            <li class="page-item">
                <a class="page-link" href="{% url 'admin_schedule' yesterday.year yesterday.month yesterday.day %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">{{day}}</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="{% url 'admin_schedule' tomorrow.year tomorrow.month tomorrow.day %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </nav>
    </td>
    <td style="width:10%">
    </td>
</table>
<div class="table-responsive">
  <table class="table table-hover table-bordered scheduler">
    <thead>
      <tr>
        <th scope="col" style="text-align:center; vertical-align:middle;">Employee</th>
        <th scope="col">
          <div class="progress headschedule">
            <div class="progress-bar" role="progressbar">9:00am</div>
            <div class="progress-bar" role="progressbar">10:00am</div>
            <div class="progress-bar" role="progressbar">11:00am</div>
            <div class="progress-bar" role="progressbar">12:00pm</div>
            <div class="progress-bar" role="progressbar">1:00pm</div>
            <div class="progress-bar" role="progressbar">2:00pm</div>
            <div class="progress-bar" role="progressbar">3:00pm</div>
            <div class="progress-bar" role="progressbar">4pm</div>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
        {% for user in day_sched %}
        {% if user.2 %}
        <tr>
            <th scope="row">{{user.0}} {{user.1}}</th>
        <td>
            <div class="progress">
                {% for t in user.2%}
                <div class="progress-bar filler" role="progressbar" style="width: {{t.1}}%"></div>
                <div class="progress-bar" role="progressbar" style="width: {{t.2}}%">{{t.0.0}} - {{t.0.1}}</div>
                {%endfor%}
            </div>
        </td>
        </tr>
        {% endif %}
        {% endfor %}

      <!-- <tr> -->
      <!-- <th scope="row">M. Farrell</th> -->
      <!-- <td> -->
      <!-- <div class="progress"> -->
      <!-- <div class="progress-bar" role="progressbar" style="width: 20%">9:00am - 10:20am</div> -->
      <!-- <div class="progress-bar filler" role="progressbar" style="width: 10%">10:20am - 11:00am</div> -->
      <!-- <div class="progress-bar unavail progress-bar-striped" role="progressbar" style="width: 15%;"></div> -->
      <!-- <div class="progress-bar" role="progressbar" style="width: 22.5%">12:00pm - 1:30pm</div> -->
      <!-- <div class="progress-bar filler" role="progressbar" style="width: 7.5%">1:30pm - 2:00pm</div> -->
      <!-- <div class="progress-bar" role="progressbar" style="width: 30%">2:00pm - 4:00pm</div> -->
      <!-- <div class="progress-bar filler" role="progressbar" style="width: 15%">4:00am - 5:00pm</div> -->
      <!-- </div> -->
      <!-- </td> -->
      <!-- </tr> -->
      <!-- <tr> -->
      <!-- <th scope="row">G. Santos</th> -->
      <!-- <td> -->
      <!-- <div class="progress"> -->
      <!-- <div class="progress-bar" role="progressbar" style="width: 45%">9:00am - 12:00pm</div> -->
      <!-- <div class="progress-bar unavail progress-bar-striped" role="progressbar" style="width: 75%"></div> -->
      <!-- </div> -->
      <!-- </td> -->
      <!-- </tr> -->
    </tbody>
  </table>
</div>

{% endblock %}

project2/Q/Cloq/templates/catalog/admin_settings.html
{% extends "template.html" %}

{% block content %}

<script>
document.getElementById("settings").className += " active";
</script>

<h1>Admin Settings</h1>
<div class="alert alert-danger" style="display:{{warn}};"><strong>Password not changed</strong>, your new password and confirmation password did not match.</div>
<div class="alert alert-success" style="display:{{success}};"><strong>Password successfully changed!</strong></div>

<div class="alert alert-danger" style="display:{{warn_newu}};"><strong>No New User</strong>: could not make a new user..</div>
<div class="alert alert-success" style="display:{{success_newu}};"><strong>New User Created!!</strong></div>

    <form action="" method="post"> {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="id_firstname">First Name</label>
		<input type="text" name="firstname" maxlength="100" id="id_firstname" class="form-control" placeholder="First Name" value="{{firstname}}" required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="id_lastname">Last Name</label>
		<input type="text" name="lastname" maxlength="100" class="form-control" id="id_lastname" placeholder="Last Name" value="{{lastname}}" required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="id_username">Username</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrepend2">@</span>
                    </div>
		    <input type="text" name="username" maxlength="30" id="id_username" class="form-control" placeholder="Username" aria-describedby="inputGroupPrepend2" value="{{username}}" readonly>
                </div>
            </div>
        </div>
	<div class="modal fade" id="passwordModal" tabindex="-1" role="dialog" aria-labelledby="passwordModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="changePasswordModalTitle">Change Password</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
	<div class="form-group">
		<label for="id_password">New Password</label>
		<input type="password" maxlength="255" id="id_password" name="password" value="" class="form-control" placeholder="New Password">
		<label for="id_cpassword">Confirm New Password</label>
		<input type="password" maxlength="255" id="id_cpassword" name="cpassword" value="" class="form-control" placeholder="Confirm New Password">
	</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal" onClick="window.location.href = window.location.href;">Cancel</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</div>
		</div>
	</div>


  <div class="modal fade" id="accountModal" tabindex="-1" role="dialog" aria-labelledby="accountModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="accountModalTitle">Create New User</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputFName">First Name</label>
                <input type="text" class="form-control" id="inputFName" name="inputFName" placeholder="Ernest">
              </div>
              <div class="form-group col-md-6">
                <label for="inputLName">Last Name</label>
                <input type="text" class="form-control" id="inputLName" name="inputLName" placeholder="Thornhill">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group">
                <label for="inputAddress">Username</label>
                <input type="username" class="form-control" id="inputUsername" name="inputUsername" placeholder="ethornhill">
              </div>
              <div class="form-group col-md-6">
                <label for="inputLName">Password</label>
                <input type="password" class="form-control" id="inputPassword" name="inputPassword" placeholder="Shhh, its a secret">
              </div>
            </div>
            <div class="form-group">
              <label for="inputAddress">Email Address</label>
              <input type="email" class="form-control" id="inputEmailAddress" name="inputEmailAddress" placeholder="ethornhill@landing.co">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" name="gridCheck" id="gridCheck">
                  <label class="form-check-label" for="gridCheck">
                    Subscribe to notifications
                  </label>
                </div>
            </div>
            <div class="form-row">
              <div class="form-group">
                <label for="inputAddress">Phone</label>
                <input type="phone" class="form-control" id="inputPhone" name="inputPhone" placeholder="+1 (888) 888-8888">
              </div>
              <div class="form-group col-md-6">
                <label for="inputLName">Pronouns</label>
                <input type="text" class="form-control" id="inputPronoun" name="inputPronoun" placeholder="they/them/theirs">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="inputUsertype">User Type</label>
                <select id="inputUsertype" class="form-control">
                  <option selected>Select...</option>
                  <option>1 - User</option>
                  <option>2 - Admin</option>
                </select>
              </div>
              <div class="form-group">
                <div class="row">
                  <legend class="col-form-label col-md-6 pt-0">Overtime?</legend>
                    <div class="col-sm-10">
                    <div class="form-check">
                      <input class="form-check-input" type="radio" name="overtimeModal" id="inputOT1" value="True" {{overtime}}>
                        <label class="form-check-label" for="inputOT1">
                          Yes
                        </label>
                      </div>
                      <div class="form-check">
                        <input class="form-check-input" type="radio" name="overtimeModal" id="inputOT2" value="False" {{notovertime}}>
                        <label class="form-check-label" for="inputOT2">
                          No
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal" onClick="window.location.href = window.location.href;">Cancel</button>
          <button type="submit" class="btn btn-primary">Create</button>
        </div>
      </div>
    </div>
  </div>


        <div class="form-group">
            <label for="id_email">Email Address</label>
	    <input type="email" maxlength="254" name="email" class="form-control" id="id_email" aria-describedby="emailHelp" placeholder="Enter email" value="{{email}}">
            <small id="emailHelp" class="form-text text-muted"><div class="form-check">
			    <input type="checkbox" name="notification" class="form-check-input" id="id_notification" {{notification}}>
                <label class="form-check-label" for="id_notification">Subscribe to notifications</label>
            </div></small>
        </div>
        <div class="form-group row">
            <label for="id_pronoun" class="col-sm-2 col-form-label col-form-label-sm">Pronouns:</label>
            <div class="col-sm-10">
		    <input type="text" id="id_pronoun" name="pronoun" maxlength="30" class="form-control form-control-sm" placeholder="xie/xier/xiers" value="{{pronoun}}">
            </div>
        </div>

        <div class="form-group row">
            <label for="id_phone" class="col-sm-2 col-form-label col-form-label-sm">Phone Number</label>
            <div class="col-sm-10">
		    <input type="text" id="id_phone" maxlength="20" name="phone" class="form-control form-control-sm" placeholder="+1 (XXX)-XXX-XXXX" value="{{phone}}">
            </div>
	</div>
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-2 pt-0">Do you want to work overtime?</legend>
                <div class="col-sm-10">
                    <div class="form-check">
			    <input class="form-check-input" type="radio" name="overtime" id="id_overtime_1" value="True" {{overtime}}>
                        <label class="form-check-label" for="id_overtime_1">
                            Yes
                        </label>
                    </div>
                    <div class="form-check">
			    <input class="form-check-input" type="radio" name="overtime" id="id_overtime_0" value="False" {{notovertime}}>
                        <label class="form-check-label" for="id_overtime_0">
                            No
                        </label>
                    </div>
		</div>
            </div>
        </fieldset>
        <!--<div class="form-group">
            <label for="exampleFormControlTextarea1">Message to manager</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
	</div>-->
	{{form.errors}}
	{{form.non_field_errors}}
	    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#passwordModal">Change Password</button>
      <button type="button" class="btn btn-info" data-toggle="modal" data-target="#accountModal">Create new user</button>
      <button type="button" class="btn btn-outline-secondary">Payroll History</button>
      <button class="btn btn-primary" type="submit">Update</button>
    </form>
{% endblock %}

project2/Q/Cloq/templates/catalog/login.html
{% load staticfiles %}
<html>
<head>
<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/signin.css' %}" />
</head>
<body class=text-center>
 <div class="container">

      <form class="form-signin" method="post" id="login-form">{% csrf_token %}
		  <img class="mb-4" src="{% static 'img/logo.gif' %}" alt="">
        <h2 class="form-signin-heading">Cloq Login</h2>
        <p class="text-muted">{{message}}</p>

        <label for="id_username" class="sr-only">Email address</label>
        <input type="text" name="username" id="id_username" class="form-control" placeholder="User Name" required autofocus>
        <label for="id_password" class="sr-only">Password</label>
        <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
        <!-- <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div> -->
		  <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
		  <p class="mt-5 mb-3 text-muted">&copy; 2018 | Cloq by Team Q</p>
      </form>

    </div>

<script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

project2/Q/Cloq/templates/catalog/user_settings.html
{% extends "template.html" %}

{% block content %}

<script>
document.getElementById("settings").className += " active";
</script>

<h1>Settings</h1>
<div class="alert alert-danger" style="display:{{warn}};"><strong>Password not changed</strong>, your new password and confirmation password did not match.</div>
<div class="alert alert-success" style="display:{{success}};"><strong>Password successfully changed!</strong></div>
    <form action="" method="post">
	    {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4 mb-3">
                <label for="id_firstname">First Name</label>
		<input type="text" name="firstname" maxlength="100" id="id_firstname" class="form-control" placeholder="First Name" value="{{firstname}}" required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="id_lastname">Last Name</label>
		<input type="text" name="lastname" maxlength="100" class="form-control" id="id_lastname" placeholder="Last Name" value="{{lastname}}" required>
            </div>
            <div class="col-md-4 mb-3">
                <label for="id_username">Username</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="inputGroupPrepend2">@</span>
                    </div>
		    <input type="text" name="username" maxlength="30" id="id_username" class="form-control" placeholder="Username" aria-describedby="inputGroupPrepend2" value="{{username}}" readonly>
                </div>
            </div>
        </div>
	<div class="modal fade" id="passwordModal" tabindex="-1" role="dialog" aria-labelledby="passwordModalCenterTitle" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title" id="changePasswordModalTitle">Change Password</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
	<div class="form-group">
		<label for="id_password">New Password</label>
		<input type="password" maxlength="255" id="id_password" name="password" value="" class="form-control" placeholder="New Password">
		<label for="id_cpassword">Confirm New Password</label>
		<input type="password" maxlength="255" id="id_cpassword" name="cpassword" value="" class="form-control" placeholder="Confirm New Password">
	</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-dismiss="modal" onClick="window.location.href = window.location.href;">Cancel</button>
					<button type="submit" class="btn btn-primary">Save</button>
				</div>
			</div>
		</div>
	</div>
        <div class="form-group">
            <label for="id_email">Email Address</label>
	    <input type="email" maxlength="254" name="email" class="form-control" id="id_email" aria-describedby="emailHelp" placeholder="Enter email" value="{{email}}">
            <small id="emailHelp" class="form-text text-muted"><div class="form-check">
			    <input type="checkbox" name="notification" class="form-check-input" id="id_notification" {{notification}}>
                <label class="form-check-label" for="id_notification">Subscribe to notifications</label>
            </div></small>
        </div>
        <div class="form-group row">
            <label for="id_pronoun" class="col-sm-2 col-form-label col-form-label-sm">Pronouns:</label>
            <div class="col-sm-10">
		    <input type="text" id="id_pronoun" name="pronoun" maxlength="30" class="form-control form-control-sm" placeholder="xie/xier/xiers" value="{{pronoun}}">
            </div>
        </div>

        <div class="form-group row">
            <label for="id_phone" class="col-sm-2 col-form-label col-form-label-sm">Phone Number</label>
            <div class="col-sm-10">
		    <input type="text" id="id_phone" maxlength="20" name="phone" class="form-control form-control-sm" placeholder="+1 (XXX)-XXX-XXXX" value="{{phone}}">
            </div>
	</div>
        <fieldset class="form-group">
            <div class="row">
                <legend class="col-form-label col-sm-2 pt-0">Do you want to work overtime?</legend>
                <div class="col-sm-10">
                    <div class="form-check">
			    <input class="form-check-input" type="radio" name="overtime" id="id_overtime_1" value="True" {{overtime}}>
                        <label class="form-check-label" for="id_overtime_1">
                            Yes
                        </label>
                    </div>
                    <div class="form-check">
			    <input class="form-check-input" type="radio" name="overtime" id="id_overtime_0" value="False" {{notovertime}}>
                        <label class="form-check-label" for="id_overtime_0">
                            No
                        </label>
                    </div>
		</div>
            </div>
        </fieldset>
        <!--<div class="form-group">
            <label for="exampleFormControlTextarea1">Message to manager</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
	</div>-->
	{{form.errors}}
	{{form.non_field_errors}}
	<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#passwordModal">Change Password</button>
        <button type="button" class="btn btn-outline-secondary">Payroll History</button>
        <button class="btn btn-primary" type="submit">Update</button>
    </form>
{% endblock %}